### ISSUE TITLE
LocalPicture插件 输入关键字bz没反应

### ISSUE THREAD

**Issue by z245045** [XJLZ/LuaPlugins#3]
大佬您好，我是一个文科小白。
我复制您localPicture.lua里面的代码，并把图片路径改成了自己的windows路径，其他的没有更改，在群里面发送bz 没有反应，请问我还需要修改哪里呢。
![photo_2020-07-25_19-16-27](https://user-images.githubusercontent.com/51532998/88455852-91426b00-ceab-11ea-9152-c15eedfe62a1.jpg)

**Comment by feilongproject** [comment]
现在Windows版不能发送图片信息了

**Comment by XJLZ** [comment]
![image](https://user-images.githubusercontent.com/28652248/92204305-c338eb00-eeb5-11ea-8bc7-0b5e6a12a396.png)
取随机数1-40，有可能没取到1.。。。。
