### ISSUE TITLE
music.lua 还是用不了

### ISSUE THREAD

**Issue by Declarcall** [XJLZ/LuaPlugins#6]
我输入:  听歌 A Promise 
OPQ log.notice 输出
```
听歌keyWord-->APromise
url-->https://c.y.qq.com/soso/fcgi-bin/client_search_cp?ct=24&qqmusic_ver=1298&new_json=1&remoteplace=txt.yqq.song&searchid=&t=0&aggr=1&cr=1&catZhida=1&lossless=0&flag_qc=0&p=1&n=20&w=APromise
songID-->002WyOma0F5H8s
songname-->A Promise（世界顶尖的暗杀者转生为异世界贵族 ED） (翻奏: 結城アイラ)
songname>A Promise（世界顶尖的暗杀者转生为异世界贵族 ED） (翻奏: 結城アイラ)
jumpUrl>https://y.qq.com/n/yqq/song/002WyOma0F5H8s.html
pic_url>http://y.gtimg.cn/music/photo_new/T002R300x300M000002GKpkd2CYreW_1.jpg?max_age=2592000
song_url>https://ws.stream.qqmusic.qq.com/
singer>Kyle Xian
```

然后就没有下文了，群里并没有收到bot发出的响应。大概是"JsonMsg"那段拼接的消息无法发出，改成"TextMsg"消息可以以文本形式发出。

我测试了下，我收发XmlMsg，JsonMsg都正常。

代码可能是未转义造成的。转义过的JsonMsg应该长这样子:
```
{"Content":"{ \"app\": \"com.tencent.structmsg\", \"config\": { \"autosize\": true, \"ctime\": 16327123456, \"forward\": true, \"token\": \"1fb46767d7ecd7cd612e5ff84ab58272\", \"type\": \"normal\" }, \"desc\": \"音乐\", \"meta\": { \"music\": { \"action\": \"\", \"android_pkg_name\": \"\", \"app_type\": 1, \"appid\": 100489085, \"desc\": \"群星\", \"jumpUrl\": \"https:\\/\\/y.music.163.com\\/m\\/song?id=28240153\u0026uct=%2B6b00Gxbo2GAXRSMERfnMA%3D%3D\u0026app_version=8.5.30\", \"musicUrl\": \"http:\\/\\/music.163.com\\/song\\/media\\/outer\\/url?id=28240153\u0026userid=123456789\u0026sc=wm\", \"preview\": \"http:\\/\\/p3.music.126.net\\/uRPcKs8NIWTfbMjnjvMKew==\\/6047313952791851.jpg\", \"sourceMsgId\": \"0\", \"source_icon\": \"\", \"source_url\": \"\", \"tag\": \"网易云音乐\", \"title\": \"难忘今宵 (Live)\" } }, \"prompt\": \"[分享]难忘今宵 (Live)\", \"ver\": \"0.0.0.1\", \"view\": \"music\" }收到[[分享]难忘今宵 (Live)]消息，请升级QQ版本查看"}
```

**Comment by XJLZ** [comment]
> 

用XML吧，json搞不定，下面有个xml的

**Comment by XJLZ** [comment]
> 我输入: 听歌 A Promise OPQ log.notice 输出
> 
> ```
> 听歌keyWord-->APromise
> url-->https://c.y.qq.com/soso/fcgi-bin/client_search_cp?ct=24&qqmusic_ver=1298&new_json=1&remoteplace=txt.yqq.song&searchid=&t=0&aggr=1&cr=1&catZhida=1&lossless=0&flag_qc=0&p=1&n=20&w=APromise
> songID-->002WyOma0F5H8s
> songname-->A Promise（世界顶尖的暗杀者转生为异世界贵族 ED） (翻奏: 結城アイラ)
> songname>A Promise（世界顶尖的暗杀者转生为异世界贵族 ED） (翻奏: 結城アイラ)
> jumpUrl>https://y.qq.com/n/yqq/song/002WyOma0F5H8s.html
> pic_url>http://y.gtimg.cn/music/photo_new/T002R300x300M000002GKpkd2CYreW_1.jpg?max_age=2592000
> song_url>https://ws.stream.qqmusic.qq.com/
> singer>Kyle Xian
> ```
> 
> 然后就没有下文了，群里并没有收到bot发出的响应。大概是"JsonMsg"那段拼接的消息无法发出，改成"TextMsg"消息可以以文本形式发出。
> 
> 我测试了下，我收发XmlMsg，JsonMsg都正常。
> 
> 代码可能是未转义造成的。转义过的JsonMsg应该长这样子:
> 
> ```
> {"Content":"{ \"app\": \"com.tencent.structmsg\", \"config\": { \"autosize\": true, \"ctime\": 16327123456, \"forward\": true, \"token\": \"1fb46767d7ecd7cd612e5ff84ab58272\", \"type\": \"normal\" }, \"desc\": \"音乐\", \"meta\": { \"music\": { \"action\": \"\", \"android_pkg_name\": \"\", \"app_type\": 1, \"appid\": 100489085, \"desc\": \"群星\", \"jumpUrl\": \"https:\\/\\/y.music.163.com\\/m\\/song?id=28240153\u0026uct=%2B6b00Gxbo2GAXRSMERfnMA%3D%3D\u0026app_version=8.5.30\", \"musicUrl\": \"http:\\/\\/music.163.com\\/song\\/media\\/outer\\/url?id=28240153\u0026userid=123456789\u0026sc=wm\", \"preview\": \"http:\\/\\/p3.music.126.net\\/uRPcKs8NIWTfbMjnjvMKew==\\/6047313952791851.jpg\", \"sourceMsgId\": \"0\", \"source_icon\": \"\", \"source_url\": \"\", \"tag\": \"网易云音乐\", \"title\": \"难忘今宵 (Live)\" } }, \"prompt\": \"[分享]难忘今宵 (Live)\", \"ver\": \"0.0.0.1\", \"view\": \"music\" }收到[[分享]难忘今宵 (Live)]消息，请升级QQ版本查看"}
> ```

用XML吧，json搞不定，下面有个xml的

**Comment by XJLZ** [comment]
或者大佬帮搞搞

**Comment by Declarcall** [comment]
是的,xml好用的。那个card.lua的测试卡片消息(JsonMsg)我也试了，发不出。

**Comment by XJLZ** [comment]
> 是的,xml好用的。那个card.lua的测试卡片消息(JsonMsg)我也试了，发不出。

里面好多都没有用了吧
