### ISSUE TITLE
ZhaNan.lua 报错

### ISSUE THREAD

**Issue by wzxyisme** [XJLZ/LuaPlugins#7]
![Snipaste_2021-12-15_22-23-14](https://user-images.githubusercontent.com/45878990/146203936-f999476b-e775-4af0-ab20-50036ba1d640.png)
如图

**Comment by XJLZ** [comment]
API挂啦

**Comment by XJLZ** [comment]
> ![Snipaste_2021-12-15_22-23-14](https://user-images.githubusercontent.com/45878990/146203936-f999476b-e775-4af0-ab20-50036ba1d640.png) 如图

API挂啦

**Comment by wzxyisme** [comment]
> > ![Snipaste_2021-12-15_22-23-14](https://user-images.githubusercontent.com/45878990/146203936-f999476b-e775-4af0-ab20-50036ba1d640.png)如图
> 
> API挂啦

截图是我更新api至https://api.lovelive.tools/api/SweetNothings/Web/1
产生的报错

**Comment by XJLZ** [comment]
> > > ![Snipaste_2021-12-15_22-23-14](https://user-images.githubusercontent.com/45878990/146203936-f999476b-e775-4af0-ab20-50036ba1d640.png)如图
> > 
> > 
> > API挂啦
> 
> 截图是我更新api至https://api.lovelive.tools/api/SweetNothings/Web/1 产生的报错

25 行 改为 local msg = info.returnObj.content

**Comment by kokorousaki** [comment]
郭楠真是
